src/Entity/Menu.php
<?php

declare(strict_types=1);

/*
 * This file is part of Wemea Menu plugin for Sylius.
 *
 * (c) Wemea (wemea.fr)
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 */

namespace Wemea\SyliusMenuPlugin\Entity;

use Sylius\Component\Resource\Model\TranslatableTrait;
use Wemea\SyliusMenuPlugin\Model\Menu as BaseMenu;

/** @psalm-suppress PropertyNotSetInConstructor */
class Menu extends BaseMenu implements MenuInterface
{
    use TranslatableTrait {
        __construct as protected initializeTranslationsCollection;
    }

    /** @var int|null */
    protected $id;

    public function __construct()
    {
        parent::__construct();
        $this->initializeTranslationsCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        /** @var MenuTranslationInterface $translation */
        $translation = $this->getTranslation();

        return $translation->getTitle();
    }

    public function setTitle(?string $title): void
    {
        /** @var MenuTranslationInterface $translation */
        $translation = $this->getTranslation();
        $translation->setTitle($title);
    }

    protected function createTranslation(): MenuTranslationInterface
    {
        return new MenuTranslation();
    }

    /**
     * Custom function to order by priority ASC but with null value at the end
     */
    public function getMenuItemsOrderByPriority(): array
    {
        //TODO : find better way to do this
        /** @var MenuItem[] $items */
        $items = $this->menuItems->toArray();

        /** @phpstan-ignore-next-line */
        uasort($items, function (MenuItem $a, MenuItem $b) {
            $priorityA = $a->getPriority();
            $priorityB = $b->getPriority();

            if ($priorityA === null && $priorityB === null) {
                return 0;
            }

            if ($priorityA === null) {
                return 1;
            }

            if ($priorityB === null) {
                return -1;
            }

            return $priorityA - $priorityB;
        });

        return $items;
    }
}

src/Form/Type/MenuType.php
<?php

declare(strict_types=1);

/*
 * This file is part of Wemea Menu plugin for Sylius.
 *
 * (c) Wemea (wemea.fr)
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 */

namespace Wemea\SyliusMenuPlugin\Form\Type;

use Sylius\Bundle\ChannelBundle\Form\Type\ChannelChoiceType;
use Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType;
use Sylius\Bundle\ResourceBundle\Form\Type\ResourceTranslationsType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class MenuType extends AbstractResourceType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('code', TextType::class, [
                'disabled' => true,
                'label' => 'sylius.ui.code',
            ])
            ->add('enabled', null, [
                'label' => 'sylius.ui.enabled',
            ])
            ->add('visibility', ChoiceType::class, [
                'label' => 'wemea_sylius_menu.ui.visibility',
                'choices' => $this->getVisibilityChoices(),
            ])
            ->add('translations', ResourceTranslationsType::class, [
                'entry_type' => MenuTranslationType::class,
            ])

            ->add('channels', ChannelChoiceType::class, [
                'multiple' => true,
                'expanded' => true,
                'label' => 'sylius.ui.channels',
                'required' => false,
            ])
        ;
    }

    public function getBlockPrefix()
    {
        return 'wemea_sylius_menu_menu';
    }

    protected function getVisibilityChoices(): array
    {
        $choices = [];

        /**
         * @var string $value
         * @var string $code
         */
        foreach ($this->dataClass::VISIBILITY_CODE as $value => $code) {
            $choices['wemea_sylius_menu.ui.visibility_label.' . $code] = $value;
        }

        return $choices;
    }
}

templates/Shop/Menu/_default.html.twig
{% if menu is not null %}
    <div {{ sylius_test_html_attribute('wemea-sylius-menu', menu.code) }}>
        <h4 {{ sylius_test_html_attribute('wemea-sylius-menu-title') }}>{{ menu.title }}</h4>

        <ul>
            {% for item in menu.menuItemsOrderByPriority %}
                <li><a class="{{ item.cssClasses ? item.cssClasses }}"
                       href="{{ wemea_sylius_menu_link_path(item.link) }}"
                       target="{{ item.target }}"
                       {% if item.description is not null %}
                           title="{{ item.description }}"
                        {% endif %}

                            {{ sylius_test_html_attribute('wemea-sylius-menu-item', item.title) }}
                    >

                        {% if item.image.path|default(null) is not null %}
                            <img src="{{ item.image.path|imagine_filter('wemea_sylius_menu_link_icon') }}">
                        {% endif %}

                        {{ item.title }}
                    </a></li>
            {% endfor %}
        </ul>
    </div>
{% endif %}